### PR TITLE
graphics/amd: use modsettings driver

### PR DESCRIPTION
**Pull request by Mic92**
See https://github.com/NixOS/nixpkgs/pull/218437

### CODE REVIEW

**Comment by Mic92** [comment]
cc @britter

**Comment by Mic92** [comment]
We use this for quite a while in nixos-hardware without any complaints. So I think this works fine. @britter let me know if this works for you.

**Comment by britter** [comment]
@Mic92 looking at the issue and the default value for `services.xserver.videoDrivers` I wonder whether it makes sense to have it in facter modules.

**Comment by Mic92** [comment]
@britter you mean because it's the default this xserver service anyway?

**Comment by britter** [comment]
@Mic92 yes exactly. What facter-modules does here seems to be no-op.

**Pull request merged**
